---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-trino
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  trino-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Trino (Iceberg)
        type: trino
        access: proxy
        url: http://trino.industrial-iot.svc.cluster.local:8080
        isDefault: false
        editable: true
        jsonData:
          catalog: iceberg
          schema: manufacturing
