---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - controller-service.yaml
  - broker-service.yaml
  - controller-statefulset.yaml
  - broker-statefulset.yaml
