---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - sources
  - minio
  - automq
  - influxdb
  - nessie
  - trino
  - iceberg-init
  - spark
  - grafana
  - kafka-ui
