---
apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: industrial-iot
  labels:
    app: nessie
spec:
  type: ClusterIP
  selector:
    app: nessie
  ports:
    - name: api
      port: 19120
      targetPort: 19120
